### ISSUE TITLE
Поправить запись в табличку ico - 

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#17]
не работает. пишет

```
Executing (default): INSERT INTO `ico_address` (`id`,`account_name`,`btc_address`,`created_at`,`updated_at`,`account_id`) VALUES (DEFAULT,'pio','1Avg9YA8bbHGJN7m1D6w8ph7yX61yNTx8R','2016-10-07 13:03:12','2016-10-07 13:03:12',6);
Unhandled rejection SequelizeForeignKeyConstraintError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`steemit_dev`.`ico_address`, CONSTRAINT `ico_address_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE)
    at Query.formatError (/home/rsteem/webclient/node_modules/sequelize/lib/dialects/mysql/query.js:168:14)
    at Query._callback (/home/rsteem/webclient/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/rsteem/webclient/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/home/rsteem/webclient/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/rsteem/webclient/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/rsteem/webclient/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/rsteem/webclient/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/rsteem/webclient/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by Undeadlol1** [comment]
Актуально? Закрываем?

**Comment by tomarcafe** [comment]
гг уже и таблички той нет
