### ISSUE TITLE
ENOENT error [babel-node ./webpack/dev-server.js]

### ISSUE THREAD

**Issue by kocherginji** [GolosChain/tolstoy#245]
Здравствуйте.
При запуске веб-клиента возникли сложности, а именно: у скрипта не получается создать файл _webpack-stats-dev.json_ в директории _tmp_. При запуске `npm start` я получаю слудующий вывод:
```
> golos.io@1.0.0 start /Users/user/projects/tolstoy
> babel-node ./webpack/dev-server.js

`webpack-dev-server` listening on port 3001
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/user/projects/tolstoy/tmp/webpack-stats-dev.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at Compiler.exports.default (/Users/user/projects/tolstoy/webpack/utils/write-stats.js:44:8)
    at Compiler.applyPlugins (/Users/user/projects/tolstoy/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/Users/user/projects/tolstoy/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/Users/user/projects/tolstoy/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/Users/user/projects/tolstoy/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/Users/user/projects/tolstoy/node_modules/webpack/lib/Compiler.js:58:19)
    at /user/projects/tolstoy/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/user/projects/tolstoy/node_modules/tapable/lib/Tapable.js:60:69)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! golos.io@1.0.0 start: `babel-node ./webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the golos.io@1.0.0 start script 'babel-node ./webpack/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the golos.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs golos.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls golos.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/projects/tolstoy/npm-debug.log
```

Буду очень признателен если поможете мне разобраться, в чем может заключаться эта проблема?

Благодарю за внимание.

**Comment by kocherginji** [comment]
Проблема решена.
Помогло - ручное создание директории _tmp_ и пустого файла _webpack-stats-dev.json_.
